package com.elytradev.fondue;

public enum Goal {
	WORK_ON_SMALL_SERVERS,
	WORK_IN_SINGLEPLAYER,
	ENCOURAGE_MAP_LONGEVITY,
	BE_UNIQUE,
	IMPROVE_VANILLA,
	ENCOURAGE_EXPLORATION,
	ENCOURAGE_SOCIALIZATION,
	ENCOURAGE_INFRASTRUCTURE
}
